app:
  name: My App Config Server test
  description: Welcome to ${app.name}
  
my:
  greeting: Hello World from config server test
  list:
    values: One, Two, Three
    
db:
  connection: "{testConnectionStringConfigServer: 'http://__', userName: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 2400